Description:  This template will deploy separate underlying stacks for VPC, EC2 instances,and RDS database

Resources:
  vpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/s3-code-repo-s3bucket-epievrtsiih7/c1-stack-vpc.yml"
  rdsStack:
    DependsOn: vpcStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/s3-code-repo-s3bucket-epievrtsiih7/c1-stack-rds.yml"
      Parameters:
        VpcId: !GetAtt vpcStack.Outputs.VPC
        SubnetId1: !GetAtt vpcStack.Outputs.PrivateSubnet1
        SubnetId2: !GetAtt vpcStack.Outputs.PrivateSubnet2
  ec2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn: rdsStack
    Properties:
      TemplateURL: "https://s3.amazonaws.com/s3-code-repo-s3bucket-epievrtsiih7/c1-stack-ec2.yml"
      Parameters:
        VpcId: !GetAtt vpcStack.Outputs.VPC
        SubnetId1: !GetAtt vpcStack.Outputs.PublicSubnet1
        SubnetId2: !GetAtt vpcStack.Outputs.PublicSubnet2
        DbHost: !GetAtt rdsStack.Outputs.DbHost
